name: vote_admin
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  dio: ^5.7.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.10+1
  go_router: ^14.3.0
  json_annotation: ^4.9.0
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.4.1

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  retrofit_generator: ^9.1.2

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/

  fonts:
    - family: SUIT
      fonts:
        - asset: fonts/SUIT-Thin.ttf
          weight: 100
        - asset: fonts/SUIT-ExtraLight.ttf
          weight: 200
        - asset: fonts/SUIT-Light.ttf
          weight: 300
        - asset: fonts/SUIT-Regular.ttf
          weight: 400
        - asset: fonts/SUIT-Medium.ttf
          weight: 500
        - asset: fonts/SUIT-SemiBold.ttf
          weight: 600
        - asset: fonts/SUIT-Bold.ttf
          weight: 700
        - asset: fonts/SUIT-ExtraBold.ttf
          weight: 800
        - asset: fonts/SUIT-Heavy.ttf
          weight: 900
